# Generated by Django 3.2 on 2022-06-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220608_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='region',
            new_name='country',
        ),
        migrations.AddField(
            model_name='product',
            name='alcohol_percentage',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
