# Generated by Django 3.2 on 2022-06-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220608_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='alcohol_percentage',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
