# Generated by Django 3.2 on 2022-06-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='body',
        ),
    ]
