# Generated by Django 3.2 on 2022-06-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_review_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product_rating',
            field=models.IntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], default=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Review Title'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_review',
            field=models.TextField(max_length=250, verbose_name='User Review'),
        ),
    ]
